const RECHARTS_DEFAULT_MARGIN = 20;

export const RECHARTS_MARGIN = {
  top: RECHARTS_DEFAULT_MARGIN,
  right: RECHARTS_DEFAULT_MARGIN,
  bottom: RECHARTS_DEFAULT_MARGIN,
  left: RECHARTS_DEFAULT_MARGIN,
};
